poll = read.csv("AnonymityPoll.csv")
table(poll$Smartphone)

table(poll$Sex, poll$Region)
table(poll$Internet.Use, poll$Smartphone)
summary(poll)
limited = subset(poll, Internet.Use == 1 | Smartphone == 1)
nrow(limited)
prop.table((table(limited$Worry.About.Info)))
prop.table(table(limited$Anonymity.Possible))
hist(limited$Age)
plot(limited$Age, limited$Info.On.Internet)
table(limited$Age, limited$Info.On.Internet)
max(table(limited$Age, limited$Info.On.Internet))
jitter(c(1, 2, 3))
plot(jitter(limited$Age), jitter(limited$Info.On.Internet))
tapply(limited$Info.On.Internet, limited$Smartphone, summary)

tapply(limited$Tried.Masking.Identity, limited$Smartphone, table)
